### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by siddhantvirus**
Fixed port number for docker command

### CODE REVIEW

**Comment by cyrildiagne** [comment]
Thanks for the PR. The default PORT in the docker image is 80: https://github.com/cyrildiagne/u2net-http/blob/master/Dockerfile#L24
What made you change to 8080?

**Comment by siddhantvirus** [comment]
Hey, the port number order is supposed to be
 ```
<host machine port>:<docker port to be exposed>
```

Hence it shouldn't be 8080:8080
It should be 8080:80

So that port 80 of the docker container is exposed to port 8080 of the host machine

**Comment by cyrildiagne** [comment]
Oh yes you're right, thanks!

**Comment by siddhantvirus** [comment]
By the way thank you for making this repository, it's really helped me :3

**Pull request merged**
